### PR TITLE
[1.2.0] Improvements and more customizations

### PR DESCRIPTION
**Pull request by Blaxou**
* `PhoneNumber` now has a `Country` attribute instead of a simple country code. Allows to access the flag and name of the country afterwards.
* Added support of a target length, by default `10`.
* Added support for a counter
* Added support for custom formatters

### CODE REVIEW

**Comment by vanshg395** [comment]
Most of these features are either already implemented or not really required like the first one.

**Comment by Blaxou** [comment]
May I disagree ? I don't really understand which ones are already implemented or not really required :

1. The formatters are really important if you want to add so kind of formatting for your numbers
2. Setting a max length and having a counter is imo more verbose than just validating
3. Having the ability to cutomize the counter is a plus 
4. The Country class is really useful, as it allows the user to retrieve other infos about the countries, not only the dial_code

I do understand that the default counter I added isn't ueful and deleted it here : https://github.com/Blaxou/intl_phone_field/commit/66cb7d5f9d962e0ff7dd66d8d2d71f3ea540ea8f

What are you thoughts on it ?

**Comment by vanshg395** [comment]
1. formatters are already there if you see formatter argument provided.
2. putting validator rather than max length is better imo because anyone can add custom validators along with maxLength within that which provides more flexibility.
4. This is a field for inputting phone number, so I don't really see any importance for any other info related to country.

**Comment by Blaxou** [comment]
1. Formatters should imo be a list like in [`TextFormField`](https://api.flutter.dev/flutter/material/TextField/inputFormatters.html)
2. Max Length allows to block the input if more than X characters are inputted, which is better than using a probably less bullet proof version of our own. And you can still provide a validator as you can see [here ](https://github.com/Blaxou/intl_phone_field/blob/e33668fe10930fa7fa58857f2895ff9834ed8b53/lib/intl_phone_field.dart#L79)
3. This is what the user of the plugin gets back, so it might be useful for him/her to have access to other infos on the country selected by the user of the app (c.f Emoji, code, etc)

**Comment by vanshg395** [comment]
3rd feature is surely not required in a phone input field, other 2 can be considered. pls send a pr after rebasing the repo first so that there are no conflicts.

**Pull request closed without merging**
