### PR TITLE
[Feature] Pass autofillHints

### PR DESCRIPTION
**Pull request by mazzonem**
Be able to pass autofillHints to the field to fill in the user's phone number automatically.

### CODE REVIEW

**Comment by CaleyD** [comment]
I'd like this behavior as well - hoping we can get it merged 🤞

**Comment by marcaureln** [comment]
Thanks @mazzonem, but this feature was shipped within a previous PR, I just merged (#243). Really appreciate.

**Comment by marcaureln** [comment]
Soon (for real)

**Comment by itsdani121** [comment]
still one year but didnot release yet. waiting for this feature

**Comment by marcaureln** [comment]
The package is deprecated now, you can have a look at the `README.md` for more info. Still, you can refer to latest code in your pubspec with this syntax: https://stackoverflow.com/questions/54022704/how-to-add-a-package-from-github-in-flutter#54023220

**Pull request closed without merging**
