### PR TITLE
IntlPhoneField - Updated deprecated properties in showDialog

### PR DESCRIPTION
**Pull request by rohankandwal**
Added ```builder``` support instead of ```child``` in ```showDialog```

### CODE REVIEW

**Review by mikiyasET — APPROVED** [review]

**Comment by mikiyasET** [comment]
can you please accept this request

**Comment by rohankandwal** [comment]
> can you please accept this request

Didn't understand, accept what?

**Review by franol-geleta — APPROVED** [review]

**Comment by herocodess** [comment]
Please merge this PR as it hinders my work progress

**Comment by vanshg395** [comment]
Same as #39 
Fixed now

**Pull request closed without merging**
