### PR TITLE
#138 Add support for region codes

### PR DESCRIPTION
**Pull request by lingster**
See #138 - this PR resolves issue #138.

We now have support for region codes and when initialising a IntlPhoneField with a full/complete number (consisting of country+region code, it will correctly remove the prefix and only display the actual number in the TextField. 

Added unit tests to verify this functions as required. Examples taken from a UK number vs Guernsey number which both have +44 prefix, but Guernsey is further identified with 1481 as the regionCode. The regionCode for other similar countries/enclaves will need to be updated in countries.dart as required.

### CODE REVIEW

**Comment by daniil-shumko** [comment]
@lingster hey, when fo you think think PR will be merged?

**Comment by lingster** [comment]
@daniil-shumko : I noticed that there are currently merge conflicts, which I will try to resolve when I have a moment and update the PR

@vanshg395 : are you still maintaining this repo, as my PR was not merged for sometime?

**Comment by marcaureln** [comment]
@lingster sorry for the delay, but big PR likes yours take time to review before merge. As you mention, there are currently conflicts. So update your PR and I'll merge it. Thanks for your contribution !

**Comment by marcaureln** [comment]
@all-contributors please add @lingster for code

**Pull request merged**
