### PR TITLE
Added validates bool parameter to onChanged callback

### PR DESCRIPTION
**Pull request by jimmyff**
There is currently no easy way to update a client app state based on if a number validates. In this PR I've exposed the validation result to the app by adding a `validates` parameter to the `onChanged` callback:

```dart
 onChanged: (PhoneNumber phone, bool validates) {
   print('${phone.completeNumber} (validates: $validates)');
 }
```

### CODE REVIEW

**Comment by jimmyff** [comment]
Hey @marcaureln - whenever is convenient could you take a look at this and let me know what you think? It's a breaking change but I think the functionality it provides is worth it.

**Comment by jimmyff** [comment]
hey @vanshg395 @marcaureln - Are you interested in this PR, if so I will resolve the conflicts. Thanks

**Comment by marcaureln** [comment]
Hey @jimmyff, I'll do my best to find an hour or two in the coming days to merge/triage PRs. Hold tight and thank you for using the package!

**Comment by marcaureln** [comment]
Hey @jimmyff, I review your PR, I have no doubt that this feature would be interesting, but it doesn't have to be a breaking change. Can you make the `validates` optional?

**Comment by jimmyff** [comment]
Hey @marcaureln sorry for the late reply on this. Somehow this notification slipped through the net. The `validates` is a bool parameter that is included when the library invokes the users `onChanged` function. As a result people would  need to update their onChanged declarations to account for this additional parameter -even if they just did something like: 
```dart
onChanged: (phone, _) {
```

I can't think of a way of making it optional unless i'm missing something obvious -which is very possible as it's been a long day!

The reason I added this feature was I had no way to update the UI in real-time as the user entered their number to indicate if it is valid or not. If there is an alternative way to achieve this I'm happy to adopt that method and move all my other countries.dart fixes in to a different PR?

**Comment by marcaureln** [comment]
Hey @jimmyff, thanks a lot for the work you are pushing in here, and sorry for the late answer. I come across a solution for your PR. I made a new branch `next` for all breaking changes. Your PR with the `validates` boolean should target the latter. And don't forget to update the changelog too. It'll make breaking changes easier to merge now.

And, I saw you add a whole new dependency. Kinda like the idea, but it should be another PR on its own. Where we can discuss the pros and cons. Also, the new PR should target the next branch (I think :thinking:)

**Comment by marcaureln** [comment]
@all-contributors please add @jimmyff for code

**Pull request closed without merging**
