### PR TITLE
Add ability to specify which countries to show in the dropdown

### PR DESCRIPTION
**Pull request by 4mitabh**
This is to handle feature requests #43.
A valid use case where the app is not available in all countries and the developer wants to restrict the list of countries to only the supported ones.

With Null safety support.

### CODE REVIEW

**Comment by wellbranding** [comment]
When this will be merged?

**Comment by 4mitabh** [comment]
> When this will be merged?

Looks like he is busy. you can override dependency to my repo in the meanwhile: 
https://github.com/4mitabh/intl_phone_field

**Comment by vanshg395** [comment]
Will publish to pub by 1st april.

**Comment by 4mitabh** [comment]
I submitted another PR. Please merge that in the next release too.
It includes fixes for some long-pending user requests.

**Pull request merged**
