### PR TITLE
Fix number of digits for Switzerland

### PR DESCRIPTION
**Pull request by grafst**
Without the leading zero, switzerland has 9 digits and not 12.

### CODE REVIEW

**Comment by marcaureln** [comment]
Wikipedia stated <<A complete telephone number consists of ten digits: 0xx xxx xx xx.>>. My question now is, are people used to fill phone forms with the leading zero. If that's the case, the max and min length should be set to 10.

**Comment by grafst** [comment]
or setting the minlength to 9 and the max to 10?

**Comment by grafst** [comment]
can we merge this?

**Comment by dev-ale** [comment]
yes please merge

**Comment by marcaureln** [comment]
Sorry for this very late answer. Nervermind, thanks for contributing.

**Pull request merged**
